const defaultThemes = {
  poolsuite: {
    name: "Retro OS (Default)",
    id: "poolsuite",
    colors: {
      "--bg-main": "#ffdad5",
      "--bg-container": "#fff8f0",
      "--bg-cell": "#ffffff",
      "--border-cell": "rgba(0, 0, 0, 0.1)",
      "--text-main": "#000000",
      "--btn-bg": "#ececec",
      "--btn-text": "#000000",
      "--btn-border": "#000000",
      "--btn-hover": "#ffffff",
      "--btn-active-bg": "#000000",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#000000",
    },
  },
  dark: {
    name: "Dark (Classic)",
    id: "dark",
    colors: {
      "--bg-main": "rgb(48, 48, 48)",
      "--bg-container": "#222",
      "--bg-cell": "#333333",
      "--border-cell": "rgba(255, 255, 255, 0.1)",
      "--text-main": "white",
      "--btn-bg": "rgb(81, 81, 81)",
      "--btn-text": "white",
      "--btn-border": "rgb(120, 120, 120)",
      "--btn-hover": "rgb(90, 90, 90)",
      "--btn-active-bg": "white",
      "--btn-active-text": "black",
      "--btn-hover-text": "white",
    },
  },
  retroLight: {
    name: "Light (Retro)",
    id: "retroLight",
    colors: {
      "--bg-main": "#f0f0f0",
      "--bg-container": "#ffffff",
      "--bg-cell": "#e0e0e0",
      "--border-cell": "rgba(0, 0, 0, 0.1)",
      "--text-main": "#333333",
      "--btn-bg": "#ffffff",
      "--btn-text": "#333333",
      "--btn-border": "#cccccc",
      "--btn-hover": "#e6e6e6",
      "--btn-active-bg": "#333333",
      "--btn-active-text": "white",
      "--btn-hover-text": "#333333",
    },
  },
  mac: {
    name: "Mac Classic",
    id: "mac",
    colors: {
      "--bg-main": "#ffffff",
      "--bg-container": "#e0e0e0",
      "--bg-cell": "#aaaaaa",
      "--border-cell": "rgba(0, 0, 0, 0.2)",
      "--text-main": "#000000",
      "--btn-bg": "#ffffff",
      "--btn-text": "#000000",
      "--btn-border": "#000000",
      "--btn-hover": "#cccccc",
      "--btn-active-bg": "#000000",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#000000",
    },
  },
  windows95: {
    name: "Windows 95",
    id: "windows95",
    colors: {
      "--bg-main": "#008080",
      "--bg-container": "#c0c0c0",
      "--bg-cell": "#ffffff",
      "--border-cell": "rgba(0, 0, 0, 0.2)",
      "--text-main": "#000000",
      "--btn-bg": "#c0c0c0",
      "--btn-text": "#000000",
      "--btn-border": "#000000",
      "--btn-hover": "#dfdfdf",
      "--btn-active-bg": "#000080",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#000000",
    },
  },
  cga: {
    name: "CGA",
    id: "cga",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#555555",
      "--bg-cell": "#AA00AA",
      "--border-cell": "rgba(255, 85, 255, 0.2)",
      "--text-main": "#55FFFF",
      "--btn-bg": "#FF55FF",
      "--btn-text": "#FFFFFF",
      "--btn-border": "#FFFFFF",
      "--btn-hover": "#AA00AA",
      "--btn-active-bg": "#55FFFF",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#FFFFFF",
    },
  },
  vaporwave: {
    name: "Vaporwave",
    id: "vaporwave",
    colors: {
      "--bg-main": "#ff71ce",
      "--bg-container": "#01cdfe",
      "--bg-cell": "#05ffa1",
      "--border-cell": "rgba(255, 113, 206, 0.2)",
      "--text-main": "#b967ff",
      "--btn-bg": "#fffb96",
      "--btn-text": "#01cdfe",
      "--btn-border": "#b967ff",
      "--btn-hover": "#ff71ce",
      "--btn-active-bg": "#05ffa1",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffffff",
    },
  },
  blueprint: {
    name: "Blueprint",
    id: "blueprint",
    colors: {
      "--bg-main": "#2a4b8d",
      "--bg-container": "#3659a2",
      "--bg-cell": "#1e3768",
      "--border-cell": "rgba(255, 255, 255, 0.1)",
      "--text-main": "#ffffff",
      "--btn-bg": "#3659a2",
      "--btn-text": "#ffffff",
      "--btn-border": "#6ba4ff",
      "--btn-hover": "#4a75c7",
      "--btn-active-bg": "#ffffff",
      "--btn-active-text": "#2a4b8d",
      "--btn-hover-text": "#ffffff",
    },
  },
  sepia: {
    name: "Sepia",
    id: "sepia",
    colors: {
      "--bg-main": "#704214",
      "--bg-container": "#d2b48c",
      "--bg-cell": "#654321",
      "--border-cell": "rgba(0, 0, 0, 0.3)",
      "--text-main": "#3e2723",
      "--btn-bg": "#d2b48c",
      "--btn-text": "#3e2723",
      "--btn-border": "#3e2723",
      "--btn-hover": "#c19a6b",
      "--btn-active-bg": "#3e2723",
      "--btn-active-text": "#d2b48c",
      "--btn-hover-text": "#3e2723",
    },
  },
  terminator: {
    name: "Terminator",
    id: "terminator",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#1a0505",
      "--bg-cell": "#1a1a1a",
      "--border-cell": "rgba(255, 0, 0, 0.3)",
      "--text-main": "#ff0000",
      "--btn-bg": "#330000",
      "--btn-text": "#ff0000",
      "--btn-border": "#ff0000",
      "--btn-hover": "#660000",
      "--btn-active-bg": "#ff0000",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffffff",
    },
  },
  ocean: {
    name: "Ocean",
    id: "ocean",
    colors: {
      "--bg-main": "#1a4b6e",
      "--bg-container": "#133854",
      "--bg-cell": "#0f2d44",
      "--border-cell": "rgba(186, 230, 253, 0.1)",
      "--text-main": "#bae6fd",
      "--btn-bg": "#0ea5e9",
      "--btn-text": "white",
      "--btn-border": "#0284c7",
      "--btn-hover": "#0284c7",
      "--btn-active-bg": "#bae6fd",
      "--btn-active-text": "#0f2d44",
      "--btn-hover-text": "white",
    },
  },
  forest: {
    name: "Forest",
    id: "forest",
    colors: {
      "--bg-main": "#2c3e38",
      "--bg-container": "#1b2925",
      "--bg-cell": "#121f1b",
      "--border-cell": "rgba(216, 245, 229, 0.1)",
      "--text-main": "#d8f5e5",
      "--btn-bg": "#4a7c68",
      "--btn-text": "#e0f2eb",
      "--btn-border": "#365c4d",
      "--btn-hover": "#59917a",
      "--btn-active-bg": "#d8f5e5",
      "--btn-active-text": "#1b2925",
      "--btn-hover-text": "#e0f2eb",
    },
  },
  sunset: {
    name: "Sunset",
    id: "sunset",
    colors: {
      "--bg-main": "#4a2c3a",
      "--bg-container": "#2e1a23",
      "--bg-cell": "#1f1118",
      "--border-cell": "rgba(255, 214, 186, 0.1)",
      "--text-main": "#ffd6ba",
      "--btn-bg": "#c45b5b",
      "--btn-text": "#fff0e6",
      "--btn-border": "#a64545",
      "--btn-hover": "#d97070",
      "--btn-active-bg": "#ffd6ba",
      "--btn-active-text": "#4a2c3a",
      "--btn-hover-text": "#fff0e6",
    },
  },
  lavender: {
    name: "Lavender",
    id: "lavender",
    colors: {
      "--bg-main": "#e6e6fa",
      "--bg-container": "#f8f8ff",
      "--bg-cell": "#dcdcdc",
      "--border-cell": "rgba(72, 61, 139, 0.1)",
      "--text-main": "#483d8b",
      "--btn-bg": "#9370db",
      "--btn-text": "white",
      "--btn-border": "#7b68ee",
      "--btn-hover": "#8a2be2",
      "--btn-active-bg": "#483d8b",
      "--btn-active-text": "white",
      "--btn-hover-text": "white",
    },
  },
  dracula: {
    name: "Dracula",
    id: "dracula",
    colors: {
      "--bg-main": "#282a36",
      "--bg-container": "#44475a",
      "--bg-cell": "#6272a4",
      "--border-cell": "rgba(189, 147, 249, 0.3)",
      "--text-main": "#f8f8f2",
      "--btn-bg": "#bd93f9",
      "--btn-text": "#282a36",
      "--btn-border": "#6272a4",
      "--btn-hover": "#ff79c6",
      "--btn-active-bg": "#f8f8f2",
      "--btn-active-text": "#282a36",
      "--btn-hover-text": "#282a36",
    },
  },
  solarizedLight: {
    name: "Solarized Light",
    id: "solarizedLight",
    colors: {
      "--bg-main": "#fdf6e3",
      "--bg-container": "#eee8d5",
      "--bg-cell": "#93a1a1",
      "--border-cell": "rgba(0, 0, 0, 0.1)",
      "--text-main": "#657b83",
      "--btn-bg": "#b58900",
      "--btn-text": "#fdf6e3",
      "--btn-border": "#93a1a1",
      "--btn-hover": "#cb4b16",
      "--btn-active-bg": "#073642",
      "--btn-active-text": "#839496",
      "--btn-hover-text": "#fdf6e3",
    },
  },
  nord: {
    name: "Nord",
    id: "nord",
    colors: {
      "--bg-main": "#2e3440",
      "--bg-container": "#3b4252",
      "--bg-cell": "#434c5e",
      "--border-cell": "rgba(143, 188, 187, 0.2)",
      "--text-main": "#d8dee9",
      "--btn-bg": "#88c0d0",
      "--btn-text": "#2e3440",
      "--btn-border": "#81a1c1",
      "--btn-hover": "#5e81ac",
      "--btn-active-bg": "#eceff4",
      "--btn-active-text": "#2e3440",
      "--btn-hover-text": "#2e3440",
    },
  },
  monokai: {
    name: "Monokai",
    id: "monokai",
    colors: {
      "--bg-main": "#272822",
      "--bg-container": "#3e3d32",
      "--bg-cell": "#75715e",
      "--border-cell": "rgba(255, 255, 255, 0.1)",
      "--text-main": "#f8f8f2",
      "--btn-bg": "#a6e22e",
      "--btn-text": "#272822",
      "--btn-border": "#f92672",
      "--btn-hover": "#66d9ef",
      "--btn-active-bg": "#ae81ff",
      "--btn-active-text": "#f8f8f2",
      "--btn-hover-text": "#272822",
    },
  },
  synthwave: {
    name: "Synthwave '84",
    id: "synthwave",
    colors: {
      "--bg-main": "#2b213a",
      "--bg-container": "#241b2f",
      "--bg-cell": "#090b20",
      "--border-cell": "rgba(255, 0, 212, 0.2)",
      "--text-main": "#fffb96",
      "--btn-bg": "#01cdfe",
      "--btn-text": "#000000",
      "--btn-border": "#05ffa1",
      "--btn-hover": "#b967ff",
      "--btn-active-bg": "#ff71ce",
      "--btn-active-text": "#2b213a",
      "--btn-hover-text": "#2b213a",
    },
  },
  matrix: {
    name: "The Matrix",
    id: "matrix",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#0d110d",
      "--bg-cell": "#002200",
      "--border-cell": "rgba(0, 255, 0, 0.1)",
      "--text-main": "#00ff00",
      "--btn-bg": "#003b00",
      "--btn-text": "#00ff00",
      "--btn-border": "#00ff00",
      "--btn-hover": "#008f11",
      "--btn-active-bg": "#00ff00",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#000000",
    },
  },
  dos: {
    name: "MS-DOS",
    id: "dos",
    colors: {
      "--bg-main": "#000084",
      "--bg-container": "#0000a8",
      "--bg-cell": "#000084",
      "--border-cell": "rgba(255, 255, 255, 0.2)",
      "--text-main": "#ffffff",
      "--btn-bg": "#aaaaaa",
      "--btn-text": "#000000",
      "--btn-border": "#ffffff",
      "--btn-hover": "#ffffff",
      "--btn-active-bg": "#000084",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#000084",
    },
  },
  gruvbox: {
    name: "Gruvbox",
    id: "gruvbox",
    colors: {
      "--bg-main": "#282828",
      "--bg-container": "#3c3836",
      "--bg-cell": "#504945",
      "--border-cell": "rgba(235, 219, 178, 0.1)",
      "--text-main": "#ebdbb2",
      "--btn-bg": "#d65d0e",
      "--btn-text": "#282828",
      "--btn-border": "#fabd2f",
      "--btn-hover": "#fe8019",
      "--btn-active-bg": "#ebdbb2",
      "--btn-active-text": "#282828",
      "--btn-hover-text": "#282828",
    },
  },
  ubuntu: {
    name: "Ubuntu",
    id: "ubuntu",
    colors: {
      "--bg-main": "#300a24",
      "--bg-container": "#4a1c38",
      "--bg-cell": "#5e2750",
      "--border-cell": "rgba(221, 72, 20, 0.2)",
      "--text-main": "#ffffff",
      "--btn-bg": "#e95420",
      "--btn-text": "#ffffff",
      "--btn-border": "#77216f",
      "--btn-hover": "#c74312",
      "--btn-active-bg": "#ffffff",
      "--btn-active-text": "#e95420",
      "--btn-hover-text": "#ffffff",
    },
  },
  highContrast: {
    name: "High Contrast",
    id: "highContrast",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#ffffff",
      "--bg-cell": "#000000",
      "--border-cell": "rgba(255, 255, 255, 0.4)",
      "--text-main": "#ffff00",
      "--btn-bg": "#0000ff",
      "--btn-text": "#ffffff",
      "--btn-border": "#ffff00",
      "--btn-hover": "#ffff00",
      "--btn-active-bg": "#ffffff",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#000000",
    },
  },
  hotdogStand: {
    name: "Hotdog Stand",
    id: "hotdogStand",
    colors: {
      "--bg-main": "#ff0000",
      "--bg-container": "#ffff00",
      "--bg-cell": "#ffcccc",
      "--border-cell": "rgba(0, 0, 0, 0.1)",
      "--text-main": "#000000",
      "--btn-bg": "#ffffff",
      "--btn-text": "#000000",
      "--btn-border": "#000000",
      "--btn-hover": "#ffff00",
      "--btn-active-bg": "#ff0000",
      "--btn-active-text": "#ffff00",
      "--btn-hover-text": "#000000",
    },
  },
  paper: {
    name: "Paper",
    id: "paper",
    colors: {
      "--bg-main": "#fdfbf7",
      "--bg-container": "#ffffff",
      "--bg-cell": "#ffffff",
      "--border-cell": "rgba(74, 144, 226, 0.2)",
      "--text-main": "#333333",
      "--btn-bg": "#ffffff",
      "--btn-text": "#333333",
      "--btn-border": "#333333",
      "--btn-hover": "#f0f0f0",
      "--btn-active-bg": "#333333",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#333333",
    },
  },
  draculaDark: {
    name: "Dracula (Deep)",
    id: "draculaDark",
    colors: {
      "--bg-main": "#1e1e24",
      "--bg-container": "#21222c",
      "--bg-cell": "#282a36",
      "--border-cell": "rgba(98, 114, 164, 0.3)",
      "--text-main": "#f8f8f2",
      "--btn-bg": "#6272a4",
      "--btn-text": "#f8f8f2",
      "--btn-border": "#bd93f9",
      "--btn-hover": "#50fa7b",
      "--btn-active-bg": "#ff5555",
      "--btn-active-text": "#f8f8f2",
      "--btn-hover-text": "#282a36",
    },
  },
  cyberpunk: {
    name: "Cyberpunk",
    id: "cyberpunk",
    colors: {
      "--bg-main": "#fceeb5",
      "--bg-container": "#000b1e",
      "--bg-cell": "#ee0000",
      "--border-cell": "rgba(0, 240, 255, 0.4)",
      "--text-main": "#00f0ff",
      "--btn-bg": "#fcdf03",
      "--btn-text": "#000000",
      "--btn-border": "#00f0ff",
      "--btn-hover": "#ee0000",
      "--btn-active-bg": "#00f0ff",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#000000",
    },
  },
  coffee: {
    name: "Coffee",
    id: "coffee",
    colors: {
      "--bg-main": "#dcc6b8",
      "--bg-container": "#6f4e37",
      "--bg-cell": "#4b3621",
      "--border-cell": "rgba(255, 255, 255, 0.2)",
      "--text-main": "#2c1b0e",
      "--btn-bg": "#8b5a2b",
      "--btn-text": "#f3e5ab",
      "--btn-border": "#4b3621",
      "--btn-hover": "#a0522d",
      "--btn-active-bg": "#dcc6b8",
      "--btn-active-text": "#4b3621",
      "--btn-hover-text": "#f3e5ab",
    },
  },
  winter: {
    name: "Winter",
    id: "winter",
    colors: {
      "--bg-main": "#f0fcff",
      "--bg-container": "#dff9fb",
      "--bg-cell": "#c7ecee",
      "--border-cell": "rgba(0, 168, 255, 0.1)",
      "--text-main": "#2f3640",
      "--btn-bg": "#7ed6df",
      "--btn-text": "#2f3640",
      "--btn-border": "#22a6b3",
      "--btn-hover": "#e056fd",
      "--btn-active-bg": "#2f3640",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#000000",
    },
  },
  mint: {
    name: "Mint",
    id: "mint",
    colors: {
      "--bg-main": "#f5fffa",
      "--bg-container": "#e0ffff",
      "--bg-cell": "#98fb98",
      "--border-cell": "rgba(0, 128, 128, 0.2)",
      "--text-main": "#2f4f4f",
      "--btn-bg": "#66cdaa",
      "--btn-text": "#f5fffa",
      "--btn-border": "#20b2aa",
      "--btn-hover": "#48d1cc",
      "--btn-active-bg": "#20b2aa",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#f5fffa",
    },
  },
  gameboy: {
    name: "GameBoy",
    id: "gameboy",
    colors: {
      "--bg-main": "#8bac0f",
      "--bg-container": "#9bbc0f",
      "--bg-cell": "#306230",
      "--border-cell": "rgba(15, 56, 15, 0.3)",
      "--text-main": "#0f380f",
      "--btn-bg": "#9bbc0f",
      "--btn-text": "#0f380f",
      "--btn-border": "#306230",
      "--btn-hover": "#8bac0f",
      "--btn-active-bg": "#0f380f",
      "--btn-active-text": "#9bbc0f",
      "--btn-hover-text": "#0f380f",
    },
  },
  gtaViceCity: {
    name: "GTA Vice City",
    id: "gtaViceCity",
    colors: {
      "--bg-main": "#ff6ec7",
      "--bg-container": "#1a0a2e",
      "--bg-cell": "#16213e",
      "--border-cell": "rgba(255, 110, 199, 0.3)",
      "--text-main": "#00fff7",
      "--btn-bg": "#00fff7",
      "--btn-text": "#1a0a2e",
      "--btn-border": "#00fff7",
      "--btn-hover": "#ff69b4",
      "--btn-active-bg": "#ff1493",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  gtaSanAndreas: {
    name: "GTA San Andreas",
    id: "gtaSanAndreas",
    colors: {
      "--bg-main": "#f4a460",
      "--bg-container": "#2d1b0e",
      "--bg-cell": "#1a0f05",
      "--border-cell": "rgba(244, 164, 96, 0.3)",
      "--text-main": "#ffd700",
      "--btn-bg": "#8b4513",
      "--btn-text": "#ffd700",
      "--btn-border": "#ffd700",
      "--btn-hover": "#cd853f",
      "--btn-active-bg": "#ffd700",
      "--btn-active-text": "#2d1b0e",
      "--btn-hover-text": "#2d1b0e",
    },
  },
  commodore64: {
    name: "Commodore 64",
    id: "commodore64",
    colors: {
      "--bg-main": "#40318d",
      "--bg-container": "#352879",
      "--bg-cell": "#6c5eb5",
      "--border-cell": "rgba(134, 122, 222, 0.3)",
      "--text-main": "#867ade",
      "--btn-bg": "#6c5eb5",
      "--btn-text": "#867ade",
      "--btn-border": "#867ade",
      "--btn-hover": "#7b6fc4",
      "--btn-active-bg": "#867ade",
      "--btn-active-text": "#352879",
      "--btn-hover-text": "#ffffff",
    },
  },
  atari: {
    name: "Atari 2600",
    id: "atari",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#3a2000",
      "--bg-cell": "#6a4a00",
      "--border-cell": "rgba(255, 165, 0, 0.2)",
      "--text-main": "#ffa500",
      "--btn-bg": "#c37b00",
      "--btn-text": "#000000",
      "--btn-border": "#ffa500",
      "--btn-hover": "#e69500",
      "--btn-active-bg": "#ffa500",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#000000",
    },
  },
  sega: {
    name: "SEGA Genesis",
    id: "sega",
    colors: {
      "--bg-main": "#0000aa",
      "--bg-container": "#000066",
      "--bg-cell": "#000044",
      "--border-cell": "rgba(255, 255, 255, 0.2)",
      "--text-main": "#ffffff",
      "--btn-bg": "#cc0000",
      "--btn-text": "#ffffff",
      "--btn-border": "#ffffff",
      "--btn-hover": "#ff3333",
      "--btn-active-bg": "#ffffff",
      "--btn-active-text": "#0000aa",
      "--btn-hover-text": "#ffffff",
    },
  },
  nes: {
    name: "NES Classic",
    id: "nes",
    colors: {
      "--bg-main": "#bcbcbc",
      "--bg-container": "#7c7c7c",
      "--bg-cell": "#f8f8f8",
      "--border-cell": "rgba(0, 0, 0, 0.3)",
      "--text-main": "#000000",
      "--btn-bg": "#cc0000",
      "--btn-text": "#ffffff",
      "--btn-border": "#000000",
      "--btn-hover": "#ff0000",
      "--btn-active-bg": "#000000",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  snes: {
    name: "SNES",
    id: "snes",
    colors: {
      "--bg-main": "#9090c0",
      "--bg-container": "#606090",
      "--bg-cell": "#d0d0e8",
      "--border-cell": "rgba(75, 0, 130, 0.2)",
      "--text-main": "#2d0060",
      "--btn-bg": "#8050a0",
      "--btn-text": "#ffffff",
      "--btn-border": "#2d0060",
      "--btn-hover": "#9060b0",
      "--btn-active-bg": "#2d0060",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  playstation: {
    name: "PlayStation",
    id: "playstation",
    colors: {
      "--bg-main": "#0070d1",
      "--bg-container": "#00439c",
      "--bg-cell": "#003087",
      "--border-cell": "rgba(255, 255, 255, 0.2)",
      "--text-main": "#ffffff",
      "--btn-bg": "#ffffff",
      "--btn-text": "#003087",
      "--btn-border": "#ffffff",
      "--btn-hover": "#e0e0e0",
      "--btn-active-bg": "#003087",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#003087",
    },
  },
  xbox: {
    name: "Xbox",
    id: "xbox",
    colors: {
      "--bg-main": "#107c10",
      "--bg-container": "#0e6b0e",
      "--bg-cell": "#094509",
      "--border-cell": "rgba(255, 255, 255, 0.2)",
      "--text-main": "#ffffff",
      "--btn-bg": "#52b043",
      "--btn-text": "#000000",
      "--btn-border": "#ffffff",
      "--btn-hover": "#7ed56f",
      "--btn-active-bg": "#ffffff",
      "--btn-active-text": "#107c10",
      "--btn-hover-text": "#000000",
    },
  },
  nintendo: {
    name: "Nintendo",
    id: "nintendo",
    colors: {
      "--bg-main": "#e60012",
      "--bg-container": "#ffffff",
      "--bg-cell": "#fce4ec",
      "--border-cell": "rgba(230, 0, 18, 0.2)",
      "--text-main": "#000000",
      "--btn-bg": "#e60012",
      "--btn-text": "#ffffff",
      "--btn-border": "#000000",
      "--btn-hover": "#ff1a2b",
      "--btn-active-bg": "#000000",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  arcade: {
    name: "Arcade",
    id: "arcade",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#1a1a2e",
      "--bg-cell": "#16213e",
      "--border-cell": "rgba(255, 255, 0, 0.2)",
      "--text-main": "#ffff00",
      "--btn-bg": "#e94560",
      "--btn-text": "#ffffff",
      "--btn-border": "#ffff00",
      "--btn-hover": "#ff6b6b",
      "--btn-active-bg": "#ffff00",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffffff",
    },
  },
  minecraft: {
    name: "Minecraft",
    id: "minecraft",
    colors: {
      "--bg-main": "#7ec850",
      "--bg-container": "#866043",
      "--bg-cell": "#8b7355",
      "--border-cell": "rgba(0, 0, 0, 0.3)",
      "--text-main": "#ffffff",
      "--btn-bg": "#565656",
      "--btn-text": "#ffffff",
      "--btn-border": "#000000",
      "--btn-hover": "#3c6e28",
      "--btn-active-bg": "#866043",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  zelda: {
    name: "Zelda",
    id: "zelda",
    colors: {
      "--bg-main": "#2e7d32",
      "--bg-container": "#1b5e20",
      "--bg-cell": "#4a5d23",
      "--border-cell": "rgba(255, 215, 0, 0.3)",
      "--text-main": "#ffd700",
      "--btn-bg": "#8bc34a",
      "--btn-text": "#1b5e20",
      "--btn-border": "#ffd700",
      "--btn-hover": "#9ccc65",
      "--btn-active-bg": "#ffd700",
      "--btn-active-text": "#1b5e20",
      "--btn-hover-text": "#1b5e20",
    },
  },
  mario: {
    name: "Super Mario",
    id: "mario",
    colors: {
      "--bg-main": "#5c94fc",
      "--bg-container": "#fcbcb0",
      "--bg-cell": "#88d800",
      "--border-cell": "rgba(0, 0, 0, 0.2)",
      "--text-main": "#000000",
      "--btn-bg": "#e52521",
      "--btn-text": "#ffffff",
      "--btn-border": "#000000",
      "--btn-hover": "#ff3b30",
      "--btn-active-bg": "#fbd000",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffffff",
    },
  },
  pacman: {
    name: "Pac-Man",
    id: "pacman",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#21177d",
      "--bg-cell": "#2121de",
      "--border-cell": "rgba(255, 255, 0, 0.3)",
      "--text-main": "#ffff00",
      "--btn-bg": "#ff0000",
      "--btn-text": "#ffffff",
      "--btn-border": "#ffff00",
      "--btn-hover": "#ff6699",
      "--btn-active-bg": "#ffff00",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffffff",
    },
  },
  tetris: {
    name: "Tetris",
    id: "tetris",
    colors: {
      "--bg-main": "#9ead86",
      "--bg-container": "#8e9c76",
      "--bg-cell": "#7d8b66",
      "--border-cell": "rgba(0, 0, 0, 0.3)",
      "--text-main": "#1d1f0f",
      "--btn-bg": "#c8d4ac",
      "--btn-text": "#1d1f0f",
      "--btn-border": "#000000",
      "--btn-hover": "#d8e4bc",
      "--btn-active-bg": "#1d1f0f",
      "--btn-active-text": "#c8d4ac",
      "--btn-hover-text": "#1d1f0f",
    },
  },
  portal: {
    name: "Portal",
    id: "portal",
    colors: {
      "--bg-main": "#2c2c2c",
      "--bg-container": "#1a1a1a",
      "--bg-cell": "#3d3d3d",
      "--border-cell": "rgba(0, 162, 255, 0.3)",
      "--text-main": "#ffffff",
      "--btn-bg": "#00a2ff",
      "--btn-text": "#ffffff",
      "--btn-border": "#ff6600",
      "--btn-hover": "#ff6600",
      "--btn-active-bg": "#ff6600",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  fallout: {
    name: "Fallout",
    id: "fallout",
    colors: {
      "--bg-main": "#0a0a0a",
      "--bg-container": "#1a1a1a",
      "--bg-cell": "#0d0d0d",
      "--border-cell": "rgba(18, 255, 128, 0.2)",
      "--text-main": "#12ff80",
      "--btn-bg": "#2a2a2a",
      "--btn-text": "#12ff80",
      "--btn-border": "#12ff80",
      "--btn-hover": "#3a3a3a",
      "--btn-active-bg": "#12ff80",
      "--btn-active-text": "#0a0a0a",
      "--btn-hover-text": "#12ff80",
    },
  },
  amberTerminal: {
    name: "Amber Terminal",
    id: "amberTerminal",
    colors: {
      "--bg-main": "#0d0208",
      "--bg-container": "#1a0510",
      "--bg-cell": "#0d0208",
      "--border-cell": "rgba(255, 176, 0, 0.2)",
      "--text-main": "#ffb000",
      "--btn-bg": "#2d1a00",
      "--btn-text": "#ffb000",
      "--btn-border": "#ffb000",
      "--btn-hover": "#3d2a00",
      "--btn-active-bg": "#ffb000",
      "--btn-active-text": "#0d0208",
      "--btn-hover-text": "#ffb000",
    },
  },
  outrun: {
    name: "Outrun",
    id: "outrun",
    colors: {
      "--bg-main": "#2d1f4e",
      "--bg-container": "#1a1030",
      "--bg-cell": "#0f0820",
      "--border-cell": "rgba(255, 0, 128, 0.3)",
      "--text-main": "#ff0080",
      "--btn-bg": "#00ffff",
      "--btn-text": "#1a1030",
      "--btn-border": "#00ffff",
      "--btn-hover": "#ff0080",
      "--btn-active-bg": "#ff6600",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ffffff",
    },
  },
  miami: {
    name: "Miami",
    id: "miami",
    colors: {
      "--bg-main": "#f4a7b9",
      "--bg-container": "#a5dee5",
      "--bg-cell": "#e0ffcd",
      "--border-cell": "rgba(255, 107, 107, 0.2)",
      "--text-main": "#ff6b6b",
      "--btn-bg": "#feceab",
      "--btn-text": "#ff6b6b",
      "--btn-border": "#ff6b6b",
      "--btn-hover": "#ffdfc8",
      "--btn-active-bg": "#ff6b6b",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#ff6b6b",
    },
  },
  neonNights: {
    name: "Neon Nights",
    id: "neonNights",
    colors: {
      "--bg-main": "#0f0f1a",
      "--bg-container": "#1a1a2e",
      "--bg-cell": "#0a0a15",
      "--border-cell": "rgba(0, 255, 136, 0.3)",
      "--text-main": "#00ff88",
      "--btn-bg": "#ff0055",
      "--btn-text": "#ffffff",
      "--btn-border": "#00ff88",
      "--btn-hover": "#ff3377",
      "--btn-active-bg": "#00ff88",
      "--btn-active-text": "#0f0f1a",
      "--btn-hover-text": "#ffffff",
    },
  },
  retrowave: {
    name: "Retrowave",
    id: "retrowave",
    colors: {
      "--bg-main": "#2d132c",
      "--bg-container": "#801336",
      "--bg-cell": "#c72c41",
      "--border-cell": "rgba(238, 66, 102, 0.3)",
      "--text-main": "#ee4266",
      "--btn-bg": "#ffd23f",
      "--btn-text": "#2d132c",
      "--btn-border": "#ee4266",
      "--btn-hover": "#ffe066",
      "--btn-active-bg": "#ee4266",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#2d132c",
    },
  },
  hackerGold: {
    name: "Hacker Gold",
    id: "hackerGold",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#0a0a0a",
      "--bg-cell": "#050505",
      "--border-cell": "rgba(255, 215, 0, 0.2)",
      "--text-main": "#ffd700",
      "--btn-bg": "#1a1a00",
      "--btn-text": "#ffd700",
      "--btn-border": "#ffd700",
      "--btn-hover": "#2a2a00",
      "--btn-active-bg": "#ffd700",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffd700",
    },
  },
  sunset80s: {
    name: "80s Sunset",
    id: "sunset80s",
    colors: {
      "--bg-main": "#ff6b35",
      "--bg-container": "#f72585",
      "--bg-cell": "#7209b7",
      "--border-cell": "rgba(72, 149, 239, 0.3)",
      "--text-main": "#4895ef",
      "--btn-bg": "#4cc9f0",
      "--btn-text": "#3a0ca3",
      "--btn-border": "#4895ef",
      "--btn-hover": "#7ae7ff",
      "--btn-active-bg": "#f72585",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#3a0ca3",
    },
  },
  spaceInvaders: {
    name: "Space Invaders",
    id: "spaceInvaders",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#111111",
      "--bg-cell": "#000000",
      "--border-cell": "rgba(0, 255, 0, 0.3)",
      "--text-main": "#00ff00",
      "--btn-bg": "#00ff00",
      "--btn-text": "#000000",
      "--btn-border": "#00ff00",
      "--btn-hover": "#00cc00",
      "--btn-active-bg": "#ffffff",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#000000",
    },
  },
  donkeyKong: {
    name: "Donkey Kong",
    id: "donkeyKong",
    colors: {
      "--bg-main": "#000000",
      "--bg-container": "#330000",
      "--bg-cell": "#660000",
      "--border-cell": "rgba(255, 204, 0, 0.3)",
      "--text-main": "#ffcc00",
      "--btn-bg": "#ff0000",
      "--btn-text": "#ffffff",
      "--btn-border": "#ffcc00",
      "--btn-hover": "#cc0000",
      "--btn-active-bg": "#ffcc00",
      "--btn-active-text": "#000000",
      "--btn-hover-text": "#ffffff",
    },
  },
  streetFighter: {
    name: "Street Fighter",
    id: "streetFighter",
    colors: {
      "--bg-main": "#1a1a2e",
      "--bg-container": "#16213e",
      "--bg-cell": "#0f3460",
      "--border-cell": "rgba(233, 69, 96, 0.3)",
      "--text-main": "#e94560",
      "--btn-bg": "#ffc107",
      "--btn-text": "#1a1a2e",
      "--btn-border": "#e94560",
      "--btn-hover": "#ffca2c",
      "--btn-active-bg": "#e94560",
      "--btn-active-text": "#ffffff",
      "--btn-hover-text": "#1a1a2e",
    },
  },
};

